### PR TITLE
link to this repo

### PR DESCRIPTION
**Pull request by bryangingechen**
(Because I often want to come here to PR a change.)

It would also be useful to have a link from this repo to the deployed site in the README and/or a link in the "About" section of the repo.

### CODE REVIEW

**Comment by grunweg** [comment]
Good idea about the readme/the about section. I just added the former; it seems only @jcommelin can add the latter.

**Comment by grunweg** [comment]
Thanks for proposing this! I like the idea; I'm not sure about the particular form.
In my mind, users of the queueboard may not be the ones wanting to modify it (but there's certainly overlap). Hence, I would prefer making this slightly more slightly. How about this instead:
```
    print(f"""<small>This dashboard was last updated on: {updated}<br>
        Feedback on this dashboard is welcome, for instance <a href="https://github.com/jcommelin/queueboard">directly on the github repository</a>.</small>""")
```

**Comment by grunweg** [comment]
I just pushed the above change - this is easy to change or revert, and I presume the exact wording is not critical.
So: if you prefer a different wording, please say so and we can change it!

**Comment by bryangingechen** [comment]
I'm happy with your suggestion, thanks!

**Pull request closed without merging**
